// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError('Android target options not configured.');
      case TargetPlatform.iOS:
        throw UnsupportedError('iOS target options not configured.');
      case TargetPlatform.macOS:
        throw UnsupportedError('macOS target options not configured.');
      case TargetPlatform.windows:
        throw UnsupportedError('Windows target options not configured.');
      case TargetPlatform.linux:
        throw UnsupportedError('Linux target options not configured.');
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWNt7_rKhsMnQ6zYfy829q-fndukuxrf0',
    appId: '1:358017061711:web:3f3c9c8e2ed4bf64d42b3a',
    messagingSenderId: '358017061711',
    projectId: 'hostelhunt-new',
    authDomain: 'hostelhunt-new.firebaseapp.com',
    storageBucket: 'hostelhunt-new.firebasestorage.app',
    measurementId: 'G-6T75DB966N',
  );
}